// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHkXUF9wHUcoqzaZ2V2w4or7BxU4kn1Q',
    appId: '1:698868355381:web:291c51302f2459cf42fc7c',
    messagingSenderId: '698868355381',
    projectId: 'evently-app-d7e94',
    authDomain: 'evently-app-d7e94.firebaseapp.com',
    storageBucket: 'evently-app-d7e94.firebasestorage.app',
    measurementId: 'G-243WK8GB1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsrw9ORwrqbLa-oKnO9HSSp7c37WI5G4',
    appId: '1:698868355381:android:c6fd88235f5cbd1042fc7c',
    messagingSenderId: '698868355381',
    projectId: 'evently-app-d7e94',
    storageBucket: 'evently-app-d7e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXyzbPTDkKjIeo2R8ZXgeKs7MHQPyEQus',
    appId: '1:698868355381:ios:2e0a393d14c5ad2a42fc7c',
    messagingSenderId: '698868355381',
    projectId: 'evently-app-d7e94',
    storageBucket: 'evently-app-d7e94.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXyzbPTDkKjIeo2R8ZXgeKs7MHQPyEQus',
    appId: '1:698868355381:ios:2e0a393d14c5ad2a42fc7c',
    messagingSenderId: '698868355381',
    projectId: 'evently-app-d7e94',
    storageBucket: 'evently-app-d7e94.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKHkXUF9wHUcoqzaZ2V2w4or7BxU4kn1Q',
    appId: '1:698868355381:web:f8320a7ec3ac2b5a42fc7c',
    messagingSenderId: '698868355381',
    projectId: 'evently-app-d7e94',
    authDomain: 'evently-app-d7e94.firebaseapp.com',
    storageBucket: 'evently-app-d7e94.firebasestorage.app',
    measurementId: 'G-JF3EMDLETV',
  );

}